# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rempPrototest.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1024, 600)
        Frame.setMinimumSize(QtCore.QSize(1024, 600))
        Frame.setMaximumSize(QtCore.QSize(1024, 600))
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.tabWidget = QtGui.QTabWidget(Frame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.TConnect = QtGui.QWidget()
        self.TConnect.setObjectName(_fromUtf8("TConnect"))
        self.BDisconect = QtGui.QPushButton(self.TConnect)
        self.BDisconect.setGeometry(QtCore.QRect(660, 124, 221, 41))
        self.BDisconect.setObjectName(_fromUtf8("BDisconect"))
        self.CBport = QtGui.QComboBox(self.TConnect)
        self.CBport.setGeometry(QtCore.QRect(80, 84, 491, 41))
        self.CBport.setObjectName(_fromUtf8("CBport"))
        self.BConnect = QtGui.QPushButton(self.TConnect)
        self.BConnect.setGeometry(QtCore.QRect(660, 70, 221, 41))
        self.BConnect.setObjectName(_fromUtf8("BConnect"))
        self.BConectRafr = QtGui.QPushButton(self.TConnect)
        self.BConectRafr.setGeometry(QtCore.QRect(660, 184, 221, 41))
        self.BConectRafr.setObjectName(_fromUtf8("BConectRafr"))
        self.tabWidget.addTab(self.TConnect, _fromUtf8(""))
        self.TPrint = QtGui.QWidget()
        self.TPrint.setObjectName(_fromUtf8("TPrint"))
        self.LWGcode = QtGui.QListWidget(self.TPrint)
        self.LWGcode.setGeometry(QtCore.QRect(10, 10, 551, 411))
        self.LWGcode.setObjectName(_fromUtf8("LWGcode"))
        self.BPause = QtGui.QPushButton(self.TPrint)
        self.BPause.setGeometry(QtCore.QRect(760, 120, 100, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_174.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BPause.setIcon(icon)
        self.BPause.setIconSize(QtCore.QSize(40, 40))
        self.BPause.setObjectName(_fromUtf8("BPause"))
        self.BStop = QtGui.QPushButton(self.TPrint)
        self.BStop.setGeometry(QtCore.QRect(910, 120, 100, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_175.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BStop.setIcon(icon1)
        self.BStop.setIconSize(QtCore.QSize(40, 40))
        self.BStop.setObjectName(_fromUtf8("BStop"))
        self.pushButton = QtGui.QPushButton(self.TPrint)
        self.pushButton.setGeometry(QtCore.QRect(590, 210, 99, 101))
        self.pushButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_022_fire.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.BLoadPrint = QtGui.QPushButton(self.TPrint)
        self.BLoadPrint.setEnabled(True)
        self.BLoadPrint.setGeometry(QtCore.QRect(670, 50, 151, 51))
        self.BLoadPrint.setObjectName(_fromUtf8("BLoadPrint"))
        self.BPlay = QtGui.QPushButton(self.TPrint)
        self.BPlay.setGeometry(QtCore.QRect(600, 120, 100, 51))
        self.BPlay.setObjectName(_fromUtf8("BPlay"))
        self.BPrint = QtGui.QPushButton(self.TPrint)
        self.BPrint.setEnabled(True)
        self.BPrint.setGeometry(QtCore.QRect(860, 50, 151, 51))
        self.BPrint.setObjectName(_fromUtf8("BPrint"))
        self.progressBar = QtGui.QProgressBar(self.TPrint)
        self.progressBar.setGeometry(QtCore.QRect(10, 430, 1001, 121))
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty("value", 75)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.BRafrGcode = QtGui.QPushButton(self.TPrint)
        self.BRafrGcode.setGeometry(QtCore.QRect(600, 50, 41, 51))
        self.BRafrGcode.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_082.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BRafrGcode.setIcon(icon3)
        self.BRafrGcode.setIconSize(QtCore.QSize(40, 40))
        self.BRafrGcode.setObjectName(_fromUtf8("BRafrGcode"))
        self.tabWidget.addTab(self.TPrint, _fromUtf8(""))
        self.TTemp = QtGui.QWidget()
        self.TTemp.setObjectName(_fromUtf8("TTemp"))
        self.BSetExtru = QtGui.QPushButton(self.TTemp)
        self.BSetExtru.setEnabled(True)
        self.BSetExtru.setGeometry(QtCore.QRect(310, 490, 171, 41))
        self.BSetExtru.setObjectName(_fromUtf8("BSetExtru"))
        self.LTemBedC = QtGui.QLabel(self.TTemp)
        self.LTemBedC.setGeometry(QtCore.QRect(550, 490, 181, 41))
        self.LTemBedC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemBedC.setObjectName(_fromUtf8("LTemBedC"))
        self.plot = PlotWidget(self.TTemp)
        self.plot.setGeometry(QtCore.QRect(10, 10, 1001, 411))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.LTemBed = QtGui.QLabel(self.TTemp)
        self.LTemBed.setGeometry(QtCore.QRect(550, 450, 361, 31))
        self.LTemBed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemBed.setObjectName(_fromUtf8("LTemBed"))
        self.LETembed = QtGui.QLineEdit(self.TTemp)
        self.LETembed.setGeometry(QtCore.QRect(730, 490, 121, 41))
        self.LETembed.setObjectName(_fromUtf8("LETembed"))
        self.LTemExC = QtGui.QLabel(self.TTemp)
        self.LTemExC.setGeometry(QtCore.QRect(20, 490, 181, 41))
        self.LTemExC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemExC.setObjectName(_fromUtf8("LTemExC"))
        self.BSetBed = QtGui.QPushButton(self.TTemp)
        self.BSetBed.setGeometry(QtCore.QRect(870, 490, 131, 41))
        self.BSetBed.setObjectName(_fromUtf8("BSetBed"))
        self.LETemExt = QtGui.QLineEdit(self.TTemp)
        self.LETemExt.setGeometry(QtCore.QRect(170, 490, 121, 41))
        self.LETemExt.setAlignment(QtCore.Qt.AlignCenter)
        self.LETemExt.setObjectName(_fromUtf8("LETemExt"))
        self.LTemEx = QtGui.QLabel(self.TTemp)
        self.LTemEx.setGeometry(QtCore.QRect(20, 440, 321, 41))
        self.LTemEx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemEx.setObjectName(_fromUtf8("LTemEx"))
        self.tabWidget.addTab(self.TTemp, _fromUtf8(""))
        self.TControl = QtGui.QWidget()
        self.TControl.setObjectName(_fromUtf8("TControl"))
        self.BVitesse = QtGui.QPushButton(self.TControl)
        self.BVitesse.setGeometry(QtCore.QRect(450, 350, 151, 41))
        self.BVitesse.setObjectName(_fromUtf8("BVitesse"))
        self.BHY = QtGui.QPushButton(self.TControl)
        self.BHY.setGeometry(QtCore.QRect(390, 120, 61, 51))
        self.BHY.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_020_home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BHY.setIcon(icon4)
        self.BHY.setObjectName(_fromUtf8("BHY"))
        self.BMotor = QtGui.QPushButton(self.TControl)
        self.BMotor.setGeometry(QtCore.QRect(800, 60, 191, 111))
        self.BMotor.setObjectName(_fromUtf8("BMotor"))
        self.BECent = QtGui.QPushButton(self.TControl)
        self.BECent.setGeometry(QtCore.QRect(680, 210, 81, 41))
        self.BECent.setCheckable(True)
        self.BECent.setObjectName(_fromUtf8("BECent"))
        self.BED = QtGui.QPushButton(self.TControl)
        self.BED.setGeometry(QtCore.QRect(540, 210, 81, 41))
        self.BED.setCheckable(True)
        self.BED.setObjectName(_fromUtf8("BED"))
        self.BU = QtGui.QPushButton(self.TControl)
        self.BU.setGeometry(QtCore.QRect(460, 10, 111, 31))
        self.BU.setCheckable(True)
        self.BU.setChecked(True)
        self.BU.setObjectName(_fromUtf8("BU"))
        self.SFan = QtGui.QSlider(self.TControl)
        self.SFan.setGeometry(QtCore.QRect(80, 290, 341, 41))
        self.SFan.setOrientation(QtCore.Qt.Horizontal)
        self.SFan.setObjectName(_fromUtf8("SFan"))
        self.BHX = QtGui.QPushButton(self.TControl)
        self.BHX.setGeometry(QtCore.QRect(130, 120, 61, 51))
        self.BHX.setText(_fromUtf8(""))
        self.BHX.setIcon(icon4)
        self.BHX.setObjectName(_fromUtf8("BHX"))
        self.LTFan = QtGui.QLabel(self.TControl)
        self.LTFan.setGeometry(QtCore.QRect(10, 290, 67, 41))
        self.LTFan.setAlignment(QtCore.Qt.AlignCenter)
        self.LTFan.setObjectName(_fromUtf8("LTFan"))
        self.LTFlux = QtGui.QLabel(self.TControl)
        self.LTFlux.setGeometry(QtCore.QRect(10, 430, 67, 41))
        self.LTFlux.setObjectName(_fromUtf8("LTFlux"))
        self.BEC = QtGui.QPushButton(self.TControl)
        self.BEC.setGeometry(QtCore.QRect(390, 210, 81, 41))
        self.BEC.setCheckable(True)
        self.BEC.setObjectName(_fromUtf8("BEC"))
        self.BZ_2 = QtGui.QPushButton(self.TControl)
        self.BZ_2.setGeometry(QtCore.QRect(690, 60, 91, 41))
        self.BZ_2.setObjectName(_fromUtf8("BZ_2"))
        self.BD = QtGui.QPushButton(self.TControl)
        self.BD.setGeometry(QtCore.QRect(670, 10, 111, 31))
        self.BD.setCheckable(True)
        self.BD.setObjectName(_fromUtf8("BD"))
        self.BFOFF = QtGui.QPushButton(self.TControl)
        self.BFOFF.setGeometry(QtCore.QRect(800, 210, 181, 41))
        self.BFOFF.setObjectName(_fromUtf8("BFOFF"))
        self.BFan = QtGui.QPushButton(self.TControl)
        self.BFan.setGeometry(QtCore.QRect(450, 280, 161, 41))
        self.BFan.setMinimumSize(QtCore.QSize(161, 0))
        self.BFan.setObjectName(_fromUtf8("BFan"))
        self.BX = QtGui.QPushButton(self.TControl)
        self.BX.setGeometry(QtCore.QRect(60, 60, 91, 41))
        self.BX.setAutoExclusive(False)
        self.BX.setObjectName(_fromUtf8("BX"))
        self.SVitesse = QtGui.QSlider(self.TControl)
        self.SVitesse.setGeometry(QtCore.QRect(80, 350, 341, 41))
        self.SVitesse.setMaximum(200)
        self.SVitesse.setProperty("value", 100)
        self.SVitesse.setOrientation(QtCore.Qt.Horizontal)
        self.SVitesse.setObjectName(_fromUtf8("SVitesse"))
        self.BY = QtGui.QPushButton(self.TControl)
        self.BY.setGeometry(QtCore.QRect(320, 60, 91, 41))
        self.BY.setObjectName(_fromUtf8("BY"))
        self.BExtru = QtGui.QPushButton(self.TControl)
        self.BExtru.setGeometry(QtCore.QRect(40, 210, 121, 41))
        self.BExtru.setObjectName(_fromUtf8("BExtru"))
        self.BZU = QtGui.QPushButton(self.TControl)
        self.BZU.setGeometry(QtCore.QRect(270, 10, 111, 31))
        self.BZU.setCheckable(True)
        self.BZU.setObjectName(_fromUtf8("BZU"))
        self.BZ = QtGui.QPushButton(self.TControl)
        self.BZ.setGeometry(QtCore.QRect(590, 60, 91, 41))
        self.BZ.setObjectName(_fromUtf8("BZ"))
        self.BRetra = QtGui.QPushButton(self.TControl)
        self.BRetra.setGeometry(QtCore.QRect(190, 210, 131, 41))
        self.BRetra.setObjectName(_fromUtf8("BRetra"))
        self.BY_2 = QtGui.QPushButton(self.TControl)
        self.BY_2.setGeometry(QtCore.QRect(420, 60, 91, 41))
        self.BY_2.setObjectName(_fromUtf8("BY_2"))
        self.LTVitesse = QtGui.QLabel(self.TControl)
        self.LTVitesse.setGeometry(QtCore.QRect(10, 350, 67, 41))
        self.LTVitesse.setObjectName(_fromUtf8("LTVitesse"))
        self.BHZ = QtGui.QPushButton(self.TControl)
        self.BHZ.setGeometry(QtCore.QRect(650, 120, 61, 51))
        self.BHZ.setText(_fromUtf8(""))
        self.BHZ.setIcon(icon4)
        self.BHZ.setObjectName(_fromUtf8("BHZ"))
        self.BC = QtGui.QPushButton(self.TControl)
        self.BC.setGeometry(QtCore.QRect(850, 10, 111, 31))
        self.BC.setCheckable(True)
        self.BC.setObjectName(_fromUtf8("BC"))
        self.BZZU = QtGui.QPushButton(self.TControl)
        self.BZZU.setGeometry(QtCore.QRect(60, 10, 111, 31))
        self.BZZU.setCheckable(True)
        self.BZZU.setChecked(False)
        self.BZZU.setObjectName(_fromUtf8("BZZU"))
        self.BFlux = QtGui.QPushButton(self.TControl)
        self.BFlux.setGeometry(QtCore.QRect(450, 420, 151, 41))
        self.BFlux.setObjectName(_fromUtf8("BFlux"))
        self.BX_2 = QtGui.QPushButton(self.TControl)
        self.BX_2.setGeometry(QtCore.QRect(160, 60, 91, 41))
        self.BX_2.setAutoExclusive(False)
        self.BX_2.setObjectName(_fromUtf8("BX_2"))
        self.SliderFlux = QtGui.QSlider(self.TControl)
        self.SliderFlux.setGeometry(QtCore.QRect(80, 430, 341, 31))
        self.SliderFlux.setMaximum(150)
        self.SliderFlux.setSliderPosition(99)
        self.SliderFlux.setOrientation(QtCore.Qt.Horizontal)
        self.SliderFlux.setObjectName(_fromUtf8("SliderFlux"))
        self.tabWidget.addTab(self.TControl, _fromUtf8(""))
        self.TCam = QtGui.QWidget()
        self.TCam.setObjectName(_fromUtf8("TCam"))
        self.LEFps = QtGui.QLineEdit(self.TCam)
        self.LEFps.setGeometry(QtCore.QRect(780, 230, 151, 41))
        self.LEFps.setObjectName(_fromUtf8("LEFps"))
        self.CBTime = QtGui.QComboBox(self.TCam)
        self.CBTime.setGeometry(QtCore.QRect(760, 130, 181, 41))
        self.CBTime.setObjectName(_fromUtf8("CBTime"))
        self.LEDerImg = QtGui.QLineEdit(self.TCam)
        self.LEDerImg.setGeometry(QtCore.QRect(780, 330, 151, 41))
        self.LEDerImg.setObjectName(_fromUtf8("LEDerImg"))
        self.webView = QtWebKit.QWebView(self.TCam)
        self.webView.setGeometry(QtCore.QRect(10, 20, 640, 480))
        self.webView.setMouseTracking(False)
        self.webView.setAcceptDrops(True)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("http://127.0.0.1:8080/?action=snapshot")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.RBParDef = QtGui.QRadioButton(self.TCam)
        self.RBParDef.setGeometry(QtCore.QRect(770, 380, 191, 51))
        self.RBParDef.setObjectName(_fromUtf8("RBParDef"))
        self.LTime = QtGui.QLabel(self.TCam)
        self.LTime.setGeometry(QtCore.QRect(720, 80, 261, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LTime.sizePolicy().hasHeightForWidth())
        self.LTime.setSizePolicy(sizePolicy)
        self.LTime.setLineWidth(1)
        self.LTime.setScaledContents(False)
        self.LTime.setAlignment(QtCore.Qt.AlignCenter)
        self.LTime.setObjectName(_fromUtf8("LTime"))
        self.LFps = QtGui.QLabel(self.TCam)
        self.LFps.setGeometry(QtCore.QRect(800, 190, 101, 41))
        self.LFps.setAlignment(QtCore.Qt.AlignCenter)
        self.LFps.setObjectName(_fromUtf8("LFps"))
        self.BSaveTime = QtGui.QPushButton(self.TCam)
        self.BSaveTime.setGeometry(QtCore.QRect(790, 440, 131, 51))
        self.BSaveTime.setObjectName(_fromUtf8("BSaveTime"))
        self.LDerImg = QtGui.QLabel(self.TCam)
        self.LDerImg.setGeometry(QtCore.QRect(760, 270, 201, 71))
        self.LDerImg.setAlignment(QtCore.Qt.AlignCenter)
        self.LDerImg.setObjectName(_fromUtf8("LDerImg"))
        self.BRafCam = QtGui.QPushButton(self.TCam)
        self.BRafCam.setGeometry(QtCore.QRect(760, 20, 181, 51))
        self.BRafCam.setObjectName(_fromUtf8("BRafCam"))
        self.tabWidget.addTab(self.TCam, _fromUtf8(""))
        self.TTerminal = QtGui.QWidget()
        self.TTerminal.setObjectName(_fromUtf8("TTerminal"))
        self.LETerminal = QtGui.QLineEdit(self.TTerminal)
        self.LETerminal.setGeometry(QtCore.QRect(10, 460, 811, 41))
        self.LETerminal.setObjectName(_fromUtf8("LETerminal"))
        self.LWTerminal = QtGui.QListWidget(self.TTerminal)
        self.LWTerminal.setGeometry(QtCore.QRect(10, 20, 981, 421))
        self.LWTerminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWTerminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWTerminal.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.LWTerminal.setProperty("showDropIndicator", False)
        self.LWTerminal.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.LWTerminal.setObjectName(_fromUtf8("LWTerminal"))
        self.BTerminal = QtGui.QPushButton(self.TTerminal)
        self.BTerminal.setGeometry(QtCore.QRect(830, 460, 161, 41))
        self.BTerminal.setObjectName(_fromUtf8("BTerminal"))
        self.tabWidget.addTab(self.TTerminal, _fromUtf8(""))
        self.clavier = QtGui.QFrame(Frame)
        self.clavier.setGeometry(QtCore.QRect(1010, 30, 1024, 541))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setItalic(True)
        self.clavier.setFont(font)
        self.clavier.setStyleSheet(_fromUtf8("QFrame{\n"
"    background: #fafafa;\n"
"}\n"
"QPushButton{\n"
"    background-color: #8c8c8c;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 15px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 10;\n"
"    \n"
"}\n"
"QProgressBar {\n"
"    background-color: (0,255,0);\n"
"    color: red;\n"
"    width: 20px;\n"
"    margin: 0px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #38e000;\n"
"    width: 20px;\n"
"}"))
        self.clavier.setFrameShape(QtGui.QFrame.StyledPanel)
        self.clavier.setFrameShadow(QtGui.QFrame.Raised)
        self.clavier.setObjectName(_fromUtf8("clavier"))
        self.verticalLayoutWidget = QtGui.QWidget(self.clavier)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 171, 471))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.PBCG = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PBCG.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCG.setFont(font)
        self.PBCG.setObjectName(_fromUtf8("PBCG"))
        self.verticalLayout.addWidget(self.PBCG)
        self.PBCM = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PBCM.setMinimumSize(QtCore.QSize(0, 200))
        self.PBCM.setObjectName(_fromUtf8("PBCM"))
        self.verticalLayout.addWidget(self.PBCM)
        self.LEClavier = QtGui.QLineEdit(self.clavier)
        self.LEClavier.setGeometry(QtCore.QRect(10, 10, 861, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(True)
        self.LEClavier.setFont(font)
        self.LEClavier.setObjectName(_fromUtf8("LEClavier"))
        self.gridLayoutWidget = QtGui.QWidget(self.clavier)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(700, 70, 321, 381))
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(0, 60))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PBC3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC3.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC3.setObjectName(_fromUtf8("PBC3"))
        self.gridLayout.addWidget(self.PBC3, 2, 2, 1, 1)
        self.PBC1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC1.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC1.setObjectName(_fromUtf8("PBC1"))
        self.gridLayout.addWidget(self.PBC1, 2, 0, 1, 1)
        self.PBC6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC6.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC6.setObjectName(_fromUtf8("PBC6"))
        self.gridLayout.addWidget(self.PBC6, 1, 2, 1, 1)
        self.PBC2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC2.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC2.setObjectName(_fromUtf8("PBC2"))
        self.gridLayout.addWidget(self.PBC2, 2, 1, 1, 1)
        self.PBC5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC5.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC5.setObjectName(_fromUtf8("PBC5"))
        self.gridLayout.addWidget(self.PBC5, 1, 1, 1, 1)
        self.PBC9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC9.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC9.setObjectName(_fromUtf8("PBC9"))
        self.gridLayout.addWidget(self.PBC9, 0, 2, 1, 1)
        self.PBC7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC7.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC7.setObjectName(_fromUtf8("PBC7"))
        self.gridLayout.addWidget(self.PBC7, 0, 0, 1, 1)
        self.PBC4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC4.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC4.setObjectName(_fromUtf8("PBC4"))
        self.gridLayout.addWidget(self.PBC4, 1, 0, 1, 1)
        self.PBC8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC8.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC8.setObjectName(_fromUtf8("PBC8"))
        self.gridLayout.addWidget(self.PBC8, 0, 1, 1, 1)
        self.PBC0 = QtGui.QPushButton(self.gridLayoutWidget)
        self.PBC0.setMinimumSize(QtCore.QSize(0, 60))
        self.PBC0.setObjectName(_fromUtf8("PBC0"))
        self.gridLayout.addWidget(self.PBC0, 3, 1, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.clavier)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(700, 450, 321, 91))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PBCAnnuler = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.PBCAnnuler.setMinimumSize(QtCore.QSize(0, 80))
        self.PBCAnnuler.setObjectName(_fromUtf8("PBCAnnuler"))
        self.horizontalLayout.addWidget(self.PBCAnnuler)
        self.PBCEntrer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.PBCEntrer.setMinimumSize(QtCore.QSize(0, 80))
        self.PBCEntrer.setObjectName(_fromUtf8("PBCEntrer"))
        self.horizontalLayout.addWidget(self.PBCEntrer)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.clavier)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(180, 440, 511, 71))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.PBCEspace = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.PBCEspace.setMinimumSize(QtCore.QSize(0, 60))
        self.PBCEspace.setText(_fromUtf8(""))
        self.PBCEspace.setObjectName(_fromUtf8("PBCEspace"))
        self.horizontalLayout_2.addWidget(self.PBCEspace)
        self.PBCSuppr = QtGui.QPushButton(self.clavier)
        self.PBCSuppr.setGeometry(QtCore.QRect(880, 10, 131, 51))
        self.PBCSuppr.setObjectName(_fromUtf8("PBCSuppr"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.clavier)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(180, 70, 511, 381))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.PBCP = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCP.sizePolicy().hasHeightForWidth())
        self.PBCP.setSizePolicy(sizePolicy)
        self.PBCP.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCP.setFont(font)
        self.PBCP.setObjectName(_fromUtf8("PBCP"))
        self.gridLayout_2.addWidget(self.PBCP, 2, 0, 1, 1)
        self.PBCX = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCX.sizePolicy().hasHeightForWidth())
        self.PBCX.setSizePolicy(sizePolicy)
        self.PBCX.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCX.setFont(font)
        self.PBCX.setObjectName(_fromUtf8("PBCX"))
        self.gridLayout_2.addWidget(self.PBCX, 0, 0, 1, 1)
        self.PBCY = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCY.sizePolicy().hasHeightForWidth())
        self.PBCY.setSizePolicy(sizePolicy)
        self.PBCY.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCY.setFont(font)
        self.PBCY.setObjectName(_fromUtf8("PBCY"))
        self.gridLayout_2.addWidget(self.PBCY, 0, 1, 1, 1)
        self.PBCI = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCI.sizePolicy().hasHeightForWidth())
        self.PBCI.setSizePolicy(sizePolicy)
        self.PBCI.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCI.setFont(font)
        self.PBCI.setObjectName(_fromUtf8("PBCI"))
        self.gridLayout_2.addWidget(self.PBCI, 2, 1, 1, 1)
        self.PBCD = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCD.sizePolicy().hasHeightForWidth())
        self.PBCD.setSizePolicy(sizePolicy)
        self.PBCD.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCD.setFont(font)
        self.PBCD.setObjectName(_fromUtf8("PBCD"))
        self.gridLayout_2.addWidget(self.PBCD, 2, 3, 1, 1)
        self.PBCT = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCT.sizePolicy().hasHeightForWidth())
        self.PBCT.setSizePolicy(sizePolicy)
        self.PBCT.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCT.setFont(font)
        self.PBCT.setObjectName(_fromUtf8("PBCT"))
        self.gridLayout_2.addWidget(self.PBCT, 3, 3, 1, 1)
        self.PBCZ = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCZ.sizePolicy().hasHeightForWidth())
        self.PBCZ.setSizePolicy(sizePolicy)
        self.PBCZ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCZ.setFont(font)
        self.PBCZ.setFlat(False)
        self.PBCZ.setObjectName(_fromUtf8("PBCZ"))
        self.gridLayout_2.addWidget(self.PBCZ, 0, 3, 1, 1)
        self.PBCE = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCE.sizePolicy().hasHeightForWidth())
        self.PBCE.setSizePolicy(sizePolicy)
        self.PBCE.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCE.setFont(font)
        self.PBCE.setObjectName(_fromUtf8("PBCE"))
        self.gridLayout_2.addWidget(self.PBCE, 1, 0, 1, 1)
        self.PBCS = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCS.sizePolicy().hasHeightForWidth())
        self.PBCS.setSizePolicy(sizePolicy)
        self.PBCS.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCS.setFont(font)
        self.PBCS.setObjectName(_fromUtf8("PBCS"))
        self.gridLayout_2.addWidget(self.PBCS, 1, 1, 1, 1)
        self.PBCH = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCH.sizePolicy().hasHeightForWidth())
        self.PBCH.setSizePolicy(sizePolicy)
        self.PBCH.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCH.setFont(font)
        self.PBCH.setObjectName(_fromUtf8("PBCH"))
        self.gridLayout_2.addWidget(self.PBCH, 3, 1, 1, 1)
        self.PBCF = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCF.sizePolicy().hasHeightForWidth())
        self.PBCF.setSizePolicy(sizePolicy)
        self.PBCF.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCF.setFont(font)
        self.PBCF.setObjectName(_fromUtf8("PBCF"))
        self.gridLayout_2.addWidget(self.PBCF, 1, 3, 1, 1)
        self.PBCC = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCC.sizePolicy().hasHeightForWidth())
        self.PBCC.setSizePolicy(sizePolicy)
        self.PBCC.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PBCC.setFont(font)
        self.PBCC.setObjectName(_fromUtf8("PBCC"))
        self.gridLayout_2.addWidget(self.PBCC, 3, 0, 1, 1)
        self.verticalLayoutWidget.raise_()
        self.LEClavier.raise_()
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.PBCSuppr.raise_()
        self.gridLayoutWidget_2.raise_()
        self.tabWidget.raise_()
        self.clavier.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.BDisconect.setText(_translate("Frame", "Deconnecte", None))
        self.BConnect.setText(_translate("Frame", "Connection", None))
        self.BConectRafr.setText(_translate("Frame", "Rafraichir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TConnect), _translate("Frame", "Connection", None))
        self.BPause.setText(_translate("Frame", "P", None))
        self.BStop.setText(_translate("Frame", "S", None))
        self.BLoadPrint.setText(_translate("Frame", "Load", None))
        self.BPlay.setText(_translate("Frame", "Play", None))
        self.BPrint.setText(_translate("Frame", "Print", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TPrint), _translate("Frame", "Print", None))
        self.BSetExtru.setText(_translate("Frame", "Extruder", None))
        self.LTemBedC.setText(_translate("Frame", "Cible :  0", None))
        self.LTemBed.setText(_translate("Frame", "Actuel :", None))
        self.LTemExC.setText(_translate("Frame", "Cible :  0", None))
        self.BSetBed.setText(_translate("Frame", "Bed", None))
        self.LETemExt.setText(_translate("Frame", "50", None))
        self.LTemEx.setText(_translate("Frame", "Actuel :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TTemp), _translate("Frame", "Température", None))
        self.BVitesse.setText(_translate("Frame", "Vitesse", None))
        self.BMotor.setText(_translate("Frame", "Moteur Off", None))
        self.BECent.setText(_translate("Frame", "100", None))
        self.BED.setText(_translate("Frame", "10", None))
        self.BU.setText(_translate("Frame", "1", None))
        self.LTFan.setText(_translate("Frame", "0", None))
        self.LTFlux.setText(_translate("Frame", "100", None))
        self.BEC.setText(_translate("Frame", "5", None))
        self.BZ_2.setText(_translate("Frame", "Z-", None))
        self.BD.setText(_translate("Frame", "10", None))
        self.BFOFF.setText(_translate("Frame", "Fan off", None))
        self.BFan.setText(_translate("Frame", "Ventilation", None))
        self.BX.setText(_translate("Frame", "X", None))
        self.BY.setText(_translate("Frame", "Y", None))
        self.BExtru.setText(_translate("Frame", "Extrude", None))
        self.BZU.setText(_translate("Frame", "0.1", None))
        self.BZ.setText(_translate("Frame", "Z", None))
        self.BRetra.setText(_translate("Frame", "Retract", None))
        self.BY_2.setText(_translate("Frame", "Y-", None))
        self.LTVitesse.setText(_translate("Frame", "100", None))
        self.BC.setText(_translate("Frame", "100", None))
        self.BZZU.setText(_translate("Frame", "0.01", None))
        self.BFlux.setText(_translate("Frame", "Flux", None))
        self.BX_2.setText(_translate("Frame", "X-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TControl), _translate("Frame", "Control", None))
        self.RBParDef.setText(_translate("Frame", "Par defaut", None))
        self.LTime.setText(_translate("Frame", "Timelaps On/Off", None))
        self.LFps.setText(_translate("Frame", "fps", None))
        self.BSaveTime.setText(_translate("Frame", "Sauver", None))
        self.LDerImg.setText(_translate("Frame", "Derniere image", None))
        self.BRafCam.setText(_translate("Frame", "Rafraichir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TCam), _translate("Frame", "Caméra", None))
        self.LETerminal.setText(_translate("Frame", "2", None))
        self.BTerminal.setText(_translate("Frame", "Envoyer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TTerminal), _translate("Frame", "Terminal", None))
        self.PBCG.setText(_translate("Frame", "G", None))
        self.PBCM.setText(_translate("Frame", "M", None))
        self.LEClavier.setText(_translate("Frame", "M119", None))
        self.PBC3.setText(_translate("Frame", "3", None))
        self.PBC1.setText(_translate("Frame", "1", None))
        self.PBC6.setText(_translate("Frame", "6", None))
        self.PBC2.setText(_translate("Frame", "2", None))
        self.PBC5.setText(_translate("Frame", "5", None))
        self.PBC9.setText(_translate("Frame", "9", None))
        self.PBC7.setText(_translate("Frame", "7", None))
        self.PBC4.setText(_translate("Frame", "4", None))
        self.PBC8.setText(_translate("Frame", "8", None))
        self.PBC0.setText(_translate("Frame", "0", None))
        self.PBCAnnuler.setText(_translate("Frame", "Annuler", None))
        self.PBCEntrer.setText(_translate("Frame", "Entrer", None))
        self.PBCSuppr.setText(_translate("Frame", "suppr", None))
        self.PBCP.setText(_translate("Frame", "P", None))
        self.PBCX.setText(_translate("Frame", "X", None))
        self.PBCY.setText(_translate("Frame", "Y", None))
        self.PBCI.setText(_translate("Frame", "I", None))
        self.PBCD.setText(_translate("Frame", "D", None))
        self.PBCT.setText(_translate("Frame", "T", None))
        self.PBCZ.setText(_translate("Frame", "Z", None))
        self.PBCE.setText(_translate("Frame", "E", None))
        self.PBCS.setText(_translate("Frame", "S", None))
        self.PBCH.setText(_translate("Frame", "H", None))
        self.PBCF.setText(_translate("Frame", "F", None))
        self.PBCC.setText(_translate("Frame", "C", None))

from PyQt4 import QtWebKit
from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Frame = QtGui.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

