# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prtoto.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.setEnabled(True)
        TabWidget.resize(1024, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        TabWidget.setMinimumSize(QtCore.QSize(1024, 600))
        TabWidget.setMaximumSize(QtCore.QSize(1024, 600))
        TabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        TabWidget.setFont(font)
        TabWidget.setAcceptDrops(True)
        TabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        TabWidget.setTabPosition(QtGui.QTabWidget.North)
        TabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        TabWidget.setIconSize(QtCore.QSize(40, 40))
        TabWidget.setElideMode(QtCore.Qt.ElideRight)
        TabWidget.setDocumentMode(False)
        TabWidget.setTabsClosable(False)
        TabWidget.setMovable(False)
#        TabWidget.setTabBarAutoHide(False)
        self.Connection = QtGui.QWidget()
        self.Connection.setObjectName(_fromUtf8("Connection"))
        self.BConnect = QtGui.QPushButton(self.Connection)
        self.BConnect.setGeometry(QtCore.QRect(710, 36, 221, 41))
        self.BConnect.setObjectName(_fromUtf8("BConnect"))
        self.BDisconect = QtGui.QPushButton(self.Connection)
        self.BDisconect.setGeometry(QtCore.QRect(710, 90, 221, 41))
        self.BDisconect.setObjectName(_fromUtf8("BDisconect"))
        self.BConectRafr = QtGui.QPushButton(self.Connection)
        self.BConectRafr.setGeometry(QtCore.QRect(710, 150, 221, 41))
        self.BConectRafr.setObjectName(_fromUtf8("BConectRafr"))
        self.CBport = QtGui.QComboBox(self.Connection)
        self.CBport.setGeometry(QtCore.QRect(130, 50, 491, 41))
        self.CBport.setObjectName(_fromUtf8("CBport"))
        TabWidget.addTab(self.Connection, _fromUtf8(""))
        self.oprint = QtGui.QWidget()
        self.oprint.setEnabled(True)
        self.oprint.setObjectName(_fromUtf8("oprint"))
        self.BPrint = QtGui.QPushButton(self.oprint)
        self.BPrint.setEnabled(True)
        self.BPrint.setGeometry(QtCore.QRect(830, 30, 151, 51))
        self.BPrint.setObjectName(_fromUtf8("BPrint"))
        self.BLoadPrint = QtGui.QPushButton(self.oprint)
        self.BLoadPrint.setEnabled(True)
        self.BLoadPrint.setGeometry(QtCore.QRect(640, 30, 151, 51))
        self.BLoadPrint.setObjectName(_fromUtf8("BLoadPrint"))
        self.progressBar = QtGui.QProgressBar(self.oprint)
        self.progressBar.setGeometry(QtCore.QRect(30, 430, 911, 91))
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setProperty("value", 75)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.LWGcode = QtGui.QListWidget(self.oprint)
        self.LWGcode.setGeometry(QtCore.QRect(20, 10, 511, 391))
        self.LWGcode.setObjectName(_fromUtf8("LWGcode"))
        self.BPlay = QtGui.QPushButton(self.oprint)
        self.BPlay.setGeometry(QtCore.QRect(570, 100, 100, 51))
        self.BPlay.setObjectName(_fromUtf8("BPlay"))
        self.BPause = QtGui.QPushButton(self.oprint)
        self.BPause.setGeometry(QtCore.QRect(730, 100, 100, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_174.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BPause.setIcon(icon)
        self.BPause.setIconSize(QtCore.QSize(40, 40))
        self.BPause.setObjectName(_fromUtf8("BPause"))
        self.BStop = QtGui.QPushButton(self.oprint)
        self.BStop.setGeometry(QtCore.QRect(880, 100, 100, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_175.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BStop.setIcon(icon1)
        self.BStop.setIconSize(QtCore.QSize(40, 40))
        self.BStop.setObjectName(_fromUtf8("BStop"))
        self.BRafrGcode = QtGui.QPushButton(self.oprint)
        self.BRafrGcode.setGeometry(QtCore.QRect(570, 30, 41, 51))
        self.BRafrGcode.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_082.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BRafrGcode.setIcon(icon2)
        self.BRafrGcode.setIconSize(QtCore.QSize(40, 40))
        self.BRafrGcode.setObjectName(_fromUtf8("BRafrGcode"))
        self.pushButton = QtGui.QPushButton(self.oprint)
        self.pushButton.setGeometry(QtCore.QRect(560, 190, 99, 101))
        self.pushButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_022_fire.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        TabWidget.addTab(self.oprint, _fromUtf8(""))
        self.otemp = QtGui.QWidget()
        self.otemp.setObjectName(_fromUtf8("otemp"))
        self.LETemExt = QtGui.QLineEdit(self.otemp)
        self.LETemExt.setGeometry(QtCore.QRect(190, 470, 121, 41))
        self.LETemExt.setAlignment(QtCore.Qt.AlignCenter)
        self.LETemExt.setObjectName(_fromUtf8("LETemExt"))
        self.LETembed = QtGui.QLineEdit(self.otemp)
        self.LETembed.setGeometry(QtCore.QRect(700, 470, 121, 41))
        self.LETembed.setObjectName(_fromUtf8("LETembed"))
        self.BSetExtru = QtGui.QPushButton(self.otemp)
        self.BSetExtru.setEnabled(True)
        self.BSetExtru.setGeometry(QtCore.QRect(320, 470, 171, 41))
        self.BSetExtru.setObjectName(_fromUtf8("BSetExtru"))
        self.BSetBed = QtGui.QPushButton(self.otemp)
        self.BSetBed.setGeometry(QtCore.QRect(840, 470, 131, 41))
        self.BSetBed.setObjectName(_fromUtf8("BSetBed"))
        self.LTemEx = QtGui.QLabel(self.otemp)
        self.LTemEx.setGeometry(QtCore.QRect(40, 420, 321, 41))
        self.LTemEx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemEx.setObjectName(_fromUtf8("LTemEx"))
        self.LTemExC = QtGui.QLabel(self.otemp)
        self.LTemExC.setGeometry(QtCore.QRect(30, 470, 181, 41))
        self.LTemExC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemExC.setObjectName(_fromUtf8("LTemExC"))
        self.LTemBed = QtGui.QLabel(self.otemp)
        self.LTemBed.setGeometry(QtCore.QRect(510, 420, 361, 31))
        self.LTemBed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemBed.setObjectName(_fromUtf8("LTemBed"))
        self.LTemBedC = QtGui.QLabel(self.otemp)
        self.LTemBedC.setGeometry(QtCore.QRect(510, 470, 181, 41))
        self.LTemBedC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LTemBedC.setObjectName(_fromUtf8("LTemBedC"))
        self.plot = PlotWidget(self.otemp)
        self.plot.setGeometry(QtCore.QRect(20, 21, 951, 371))
        self.plot.setObjectName(_fromUtf8("plot"))
        TabWidget.addTab(self.otemp, _fromUtf8(""))
        self.ocontrole = QtGui.QWidget()
        self.ocontrole.setObjectName(_fromUtf8("ocontrole"))
        self.BZZU = QtGui.QPushButton(self.ocontrole)
        self.BZZU.setGeometry(QtCore.QRect(70, 20, 111, 31))
        self.BZZU.setCheckable(True)
        self.BZZU.setChecked(False)
        self.BZZU.setObjectName(_fromUtf8("BZZU"))
        self.BZU = QtGui.QPushButton(self.ocontrole)
        self.BZU.setGeometry(QtCore.QRect(280, 20, 111, 31))
        self.BZU.setCheckable(True)
        self.BZU.setObjectName(_fromUtf8("BZU"))
        self.BU = QtGui.QPushButton(self.ocontrole)
        self.BU.setGeometry(QtCore.QRect(470, 20, 111, 31))
        self.BU.setCheckable(True)
        self.BU.setChecked(True)
        self.BU.setObjectName(_fromUtf8("BU"))
        self.BD = QtGui.QPushButton(self.ocontrole)
        self.BD.setGeometry(QtCore.QRect(680, 20, 111, 31))
        self.BD.setCheckable(True)
        self.BD.setObjectName(_fromUtf8("BD"))
        self.BC = QtGui.QPushButton(self.ocontrole)
        self.BC.setGeometry(QtCore.QRect(860, 20, 111, 31))
        self.BC.setCheckable(True)
        self.BC.setObjectName(_fromUtf8("BC"))
        self.BX = QtGui.QPushButton(self.ocontrole)
        self.BX.setGeometry(QtCore.QRect(70, 70, 91, 41))
        self.BX.setAutoExclusive(False)
        self.BX.setObjectName(_fromUtf8("BX"))
        self.BY = QtGui.QPushButton(self.ocontrole)
        self.BY.setGeometry(QtCore.QRect(330, 70, 91, 41))
        self.BY.setObjectName(_fromUtf8("BY"))
        self.BZ_2 = QtGui.QPushButton(self.ocontrole)
        self.BZ_2.setGeometry(QtCore.QRect(700, 70, 91, 41))
        self.BZ_2.setObjectName(_fromUtf8("BZ_2"))
        self.BHX = QtGui.QPushButton(self.ocontrole)
        self.BHX.setGeometry(QtCore.QRect(140, 130, 61, 51))
        self.BHX.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("glyphicons_020_home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BHX.setIcon(icon4)
        self.BHX.setObjectName(_fromUtf8("BHX"))
        self.BHY = QtGui.QPushButton(self.ocontrole)
        self.BHY.setGeometry(QtCore.QRect(400, 130, 61, 51))
        self.BHY.setText(_fromUtf8(""))
        self.BHY.setIcon(icon4)
        self.BHY.setObjectName(_fromUtf8("BHY"))
        self.BHZ = QtGui.QPushButton(self.ocontrole)
        self.BHZ.setGeometry(QtCore.QRect(660, 130, 61, 51))
        self.BHZ.setText(_fromUtf8(""))
        self.BHZ.setIcon(icon4)
        self.BHZ.setObjectName(_fromUtf8("BHZ"))
        self.BExtru = QtGui.QPushButton(self.ocontrole)
        self.BExtru.setGeometry(QtCore.QRect(50, 220, 121, 41))
        self.BExtru.setObjectName(_fromUtf8("BExtru"))
        self.BEC = QtGui.QPushButton(self.ocontrole)
        self.BEC.setGeometry(QtCore.QRect(400, 220, 81, 41))
        self.BEC.setCheckable(True)
        self.BEC.setObjectName(_fromUtf8("BEC"))
        self.BED = QtGui.QPushButton(self.ocontrole)
        self.BED.setGeometry(QtCore.QRect(550, 220, 81, 41))
        self.BED.setCheckable(True)
        self.BED.setObjectName(_fromUtf8("BED"))
        self.BECent = QtGui.QPushButton(self.ocontrole)
        self.BECent.setGeometry(QtCore.QRect(690, 220, 81, 41))
        self.BECent.setCheckable(True)
        self.BECent.setObjectName(_fromUtf8("BECent"))
        self.BRetra = QtGui.QPushButton(self.ocontrole)
        self.BRetra.setGeometry(QtCore.QRect(200, 220, 131, 41))
        self.BRetra.setObjectName(_fromUtf8("BRetra"))
        self.BMotor = QtGui.QPushButton(self.ocontrole)
        self.BMotor.setGeometry(QtCore.QRect(810, 70, 191, 111))
        self.BMotor.setObjectName(_fromUtf8("BMotor"))
        self.BFOFF = QtGui.QPushButton(self.ocontrole)
        self.BFOFF.setGeometry(QtCore.QRect(810, 220, 181, 41))
        self.BFOFF.setObjectName(_fromUtf8("BFOFF"))
        self.BFan = QtGui.QPushButton(self.ocontrole)
        self.BFan.setGeometry(QtCore.QRect(460, 290, 161, 41))
        self.BFan.setMinimumSize(QtCore.QSize(161, 0))
        self.BFan.setObjectName(_fromUtf8("BFan"))
        self.SFan = QtGui.QSlider(self.ocontrole)
        self.SFan.setGeometry(QtCore.QRect(90, 300, 341, 41))
        self.SFan.setOrientation(QtCore.Qt.Horizontal)
        self.SFan.setObjectName(_fromUtf8("SFan"))
        self.SVitesse = QtGui.QSlider(self.ocontrole)
        self.SVitesse.setGeometry(QtCore.QRect(90, 360, 341, 41))
        self.SVitesse.setMaximum(200)
        self.SVitesse.setProperty("value", 100)
        self.SVitesse.setOrientation(QtCore.Qt.Horizontal)
        self.SVitesse.setObjectName(_fromUtf8("SVitesse"))
        self.SliderFlux = QtGui.QSlider(self.ocontrole)
        self.SliderFlux.setGeometry(QtCore.QRect(90, 440, 341, 31))
        self.SliderFlux.setMaximum(150)
        self.SliderFlux.setSliderPosition(99)
        self.SliderFlux.setOrientation(QtCore.Qt.Horizontal)
        self.SliderFlux.setObjectName(_fromUtf8("SliderFlux"))
        self.label = QtGui.QLabel(self.ocontrole)
        self.label.setGeometry(QtCore.QRect(800, 390, 141, 71))
        self.label.setObjectName(_fromUtf8("label"))
        self.BVitesse = QtGui.QPushButton(self.ocontrole)
        self.BVitesse.setGeometry(QtCore.QRect(460, 360, 151, 41))
        self.BVitesse.setObjectName(_fromUtf8("BVitesse"))
        self.BFlux = QtGui.QPushButton(self.ocontrole)
        self.BFlux.setGeometry(QtCore.QRect(460, 430, 151, 41))
        self.BFlux.setObjectName(_fromUtf8("BFlux"))
        self.BX_2 = QtGui.QPushButton(self.ocontrole)
        self.BX_2.setGeometry(QtCore.QRect(170, 70, 91, 41))
        self.BX_2.setAutoExclusive(False)
        self.BX_2.setObjectName(_fromUtf8("BX_2"))
        self.BY_2 = QtGui.QPushButton(self.ocontrole)
        self.BY_2.setGeometry(QtCore.QRect(430, 70, 91, 41))
        self.BY_2.setObjectName(_fromUtf8("BY_2"))
        self.BZ = QtGui.QPushButton(self.ocontrole)
        self.BZ.setGeometry(QtCore.QRect(600, 70, 91, 41))
        self.BZ.setObjectName(_fromUtf8("BZ"))
        self.LTFan = QtGui.QLabel(self.ocontrole)
        self.LTFan.setGeometry(QtCore.QRect(20, 300, 67, 41))
        self.LTFan.setAlignment(QtCore.Qt.AlignCenter)
        self.LTFan.setObjectName(_fromUtf8("LTFan"))
        self.LTVitesse = QtGui.QLabel(self.ocontrole)
        self.LTVitesse.setGeometry(QtCore.QRect(20, 360, 67, 41))
        self.LTVitesse.setObjectName(_fromUtf8("LTVitesse"))
        self.LTFlux = QtGui.QLabel(self.ocontrole)
        self.LTFlux.setGeometry(QtCore.QRect(20, 440, 67, 41))
        self.LTFlux.setObjectName(_fromUtf8("LTFlux"))
        TabWidget.addTab(self.ocontrole, _fromUtf8(""))
        self.ocam = QtGui.QWidget()
        self.ocam.setObjectName(_fromUtf8("ocam"))
        self.webView = QtWebKit.QWebView(self.ocam)
        self.webView.setGeometry(QtCore.QRect(30, 40, 640, 480))
        self.webView.setMouseTracking(False)
        self.webView.setAcceptDrops(True)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("http://127.0.0.1:8080/?action=snapshot")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.LTime = QtGui.QLabel(self.ocam)
        self.LTime.setGeometry(QtCore.QRect(740, 100, 261, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LTime.sizePolicy().hasHeightForWidth())
        self.LTime.setSizePolicy(sizePolicy)
        self.LTime.setLineWidth(1)
        self.LTime.setScaledContents(False)
        self.LTime.setAlignment(QtCore.Qt.AlignCenter)
        self.LTime.setObjectName(_fromUtf8("LTime"))
        self.BSaveTime = QtGui.QPushButton(self.ocam)
        self.BSaveTime.setGeometry(QtCore.QRect(810, 460, 131, 51))
        self.BSaveTime.setObjectName(_fromUtf8("BSaveTime"))
        self.LDerImg = QtGui.QLabel(self.ocam)
        self.LDerImg.setGeometry(QtCore.QRect(780, 290, 201, 71))
        self.LDerImg.setAlignment(QtCore.Qt.AlignCenter)
        self.LDerImg.setObjectName(_fromUtf8("LDerImg"))
        self.LFps = QtGui.QLabel(self.ocam)
        self.LFps.setGeometry(QtCore.QRect(820, 210, 101, 41))
        self.LFps.setAlignment(QtCore.Qt.AlignCenter)
        self.LFps.setObjectName(_fromUtf8("LFps"))
        self.RBParDef = QtGui.QRadioButton(self.ocam)
        self.RBParDef.setGeometry(QtCore.QRect(790, 400, 191, 51))
        self.RBParDef.setObjectName(_fromUtf8("RBParDef"))
        self.LEFps = QtGui.QLineEdit(self.ocam)
        self.LEFps.setGeometry(QtCore.QRect(800, 250, 151, 41))
        self.LEFps.setObjectName(_fromUtf8("LEFps"))
        self.LEDerImg = QtGui.QLineEdit(self.ocam)
        self.LEDerImg.setGeometry(QtCore.QRect(800, 350, 151, 41))
        self.LEDerImg.setObjectName(_fromUtf8("LEDerImg"))
        self.CBTime = QtGui.QComboBox(self.ocam)
        self.CBTime.setGeometry(QtCore.QRect(780, 150, 181, 41))
        self.CBTime.setObjectName(_fromUtf8("CBTime"))
        self.BRafCam = QtGui.QPushButton(self.ocam)
        self.BRafCam.setGeometry(QtCore.QRect(780, 40, 181, 51))
        self.BRafCam.setObjectName(_fromUtf8("BRafCam"))
        TabWidget.addTab(self.ocam, _fromUtf8(""))
        self.oterminal = QtGui.QWidget()
        self.oterminal.setObjectName(_fromUtf8("oterminal"))
        self.LETerminal = QtGui.QLineEdit(self.oterminal)
        self.LETerminal.setGeometry(QtCore.QRect(20, 450, 811, 41))
        self.LETerminal.setObjectName(_fromUtf8("LETerminal"))
        self.BTerminal = QtGui.QPushButton(self.oterminal)
        self.BTerminal.setGeometry(QtCore.QRect(840, 450, 161, 41))
        self.BTerminal.setObjectName(_fromUtf8("BTerminal"))
        self.LWTerminal = QtGui.QListWidget(self.oterminal)
        self.LWTerminal.setGeometry(QtCore.QRect(20, 10, 981, 421))
        self.LWTerminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWTerminal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LWTerminal.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.LWTerminal.setProperty("showDropIndicator", False)
        self.LWTerminal.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.LWTerminal.setObjectName(_fromUtf8("LWTerminal"))
        TabWidget.addTab(self.oterminal, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.BConnect.setText(_translate("TabWidget", "Connection", None))
        self.BDisconect.setText(_translate("TabWidget", "Deconnecte", None))
        self.BConectRafr.setText(_translate("TabWidget", "Rafraichir", None))
        TabWidget.setTabText(TabWidget.indexOf(self.Connection), _translate("TabWidget", "Connection", None))
        self.BPrint.setText(_translate("TabWidget", "Print", None))
        self.BLoadPrint.setText(_translate("TabWidget", "Load", None))
        self.BPlay.setText(_translate("TabWidget", "Play", None))
        self.BPause.setText(_translate("TabWidget", "P", None))
        self.BStop.setText(_translate("TabWidget", "S", None))
        TabWidget.setTabText(TabWidget.indexOf(self.oprint), _translate("TabWidget", "Print", None))
        self.LETemExt.setText(_translate("TabWidget", "50", None))
        self.BSetExtru.setText(_translate("TabWidget", "Extruder", None))
        self.BSetBed.setText(_translate("TabWidget", "Bed", None))
        self.LTemEx.setText(_translate("TabWidget", "Actuel :", None))
        self.LTemExC.setText(_translate("TabWidget", "Cible :  0", None))
        self.LTemBed.setText(_translate("TabWidget", "Actuel :", None))
        self.LTemBedC.setText(_translate("TabWidget", "Cible :  0", None))
        TabWidget.setTabText(TabWidget.indexOf(self.otemp), _translate("TabWidget", "Température", None))
        self.BZZU.setText(_translate("TabWidget", "0.01", None))
        self.BZU.setText(_translate("TabWidget", "0.1", None))
        self.BU.setText(_translate("TabWidget", "1", None))
        self.BD.setText(_translate("TabWidget", "10", None))
        self.BC.setText(_translate("TabWidget", "100", None))
        self.BX.setText(_translate("TabWidget", "X", None))
        self.BY.setText(_translate("TabWidget", "Y", None))
        self.BZ_2.setText(_translate("TabWidget", "Z-", None))
        self.BExtru.setText(_translate("TabWidget", "Extrude", None))
        self.BEC.setText(_translate("TabWidget", "5", None))
        self.BED.setText(_translate("TabWidget", "10", None))
        self.BECent.setText(_translate("TabWidget", "100", None))
        self.BRetra.setText(_translate("TabWidget", "Retract", None))
        self.BMotor.setText(_translate("TabWidget", "Moteur Off", None))
        self.BFOFF.setText(_translate("TabWidget", "Fan off", None))
        self.BFan.setText(_translate("TabWidget", "Ventilation", None))
        self.label.setText(_translate("TabWidget", "TextLabel", None))
        self.BVitesse.setText(_translate("TabWidget", "Vitesse", None))
        self.BFlux.setText(_translate("TabWidget", "Flux", None))
        self.BX_2.setText(_translate("TabWidget", "X-", None))
        self.BY_2.setText(_translate("TabWidget", "Y-", None))
        self.BZ.setText(_translate("TabWidget", "Z", None))
        self.LTFan.setText(_translate("TabWidget", "0", None))
        self.LTVitesse.setText(_translate("TabWidget", "100", None))
        self.LTFlux.setText(_translate("TabWidget", "100", None))
        TabWidget.setTabText(TabWidget.indexOf(self.ocontrole), _translate("TabWidget", "Controle", None))
        self.LTime.setText(_translate("TabWidget", "Timelaps On/Off", None))
        self.BSaveTime.setText(_translate("TabWidget", "Sauver", None))
        self.LDerImg.setText(_translate("TabWidget", "Derniere image", None))
        self.LFps.setText(_translate("TabWidget", "fps", None))
        self.RBParDef.setText(_translate("TabWidget", "Par defaut", None))
        self.BRafCam.setText(_translate("TabWidget", "Rafraichir", None))
        TabWidget.setTabText(TabWidget.indexOf(self.ocam), _translate("TabWidget", "Caméra", None))
        self.LETerminal.setText(_translate("TabWidget", "2", None))
        self.BTerminal.setText(_translate("TabWidget", "Envoyer", None))
        TabWidget.setTabText(TabWidget.indexOf(self.oterminal), _translate("TabWidget", "Terminal", None))

from PyQt4 import QtWebKit
from pyqtgraph import PlotWidget
